name: app_base
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
#command to upgrade all packages version: flutter pub upgrade --major-versions

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  path: ^1.8.0
  logger: ^2.0.1

  dio: ^5.5.0+1

  dio_http_cache_extension:
    git:
      url: https://github.com/haphu4247/dio-http-cache-extension.git
      ref: main # branch name

  fluttertoast: ^8.0.9
  equatable: ^2.0.5
  path_provider: ^2.1.0
  talker_flutter: ^4.1.5
  talker_dio_logger: ^4.1.5

  shared_preferences: ^2.0.15
  encrypt: ^5.0.1
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

