# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :deploy_staging do
    firebase_app_distribution(
        app: ENV["FIREBASE_ANDROID_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        apk_path: "../build/app/outputs/flutter-apk/app-staging-release.apk",
        groups: "base-testers"
    )
  end
  
  lane :deploy_dev do
    firebase_app_distribution(
        app: ENV["FIREBASE_ANDROID_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        apk_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
        groups: "base-testers"
    )
  end

  lane :deploy_prod do
    firebase_app_distribution(
        app: ENV["FIREBASE_ANDROID_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        apk_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
        groups: "base-testers"
    )
    upload_to_play_store
  end
end
