# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.10.1]
    steps:
      
      # The flutter action needs java so include it
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      - name: Flutter SDK Install
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ matrix.sdk }}
          channel: 'stable'
      
      # check out project
      - uses: actions/checkout@v3

      - name: Check Flutter SDK Version
        working-directory: ./base_flutter
        run: flutter --version

      - name: Install dependencies
        working-directory: ./base_flutter
        run: flutter pub get
      
      - name: Generate Text
        working-directory: ./base_flutter
        run: flutter gen-l10n --arb-dir lib/shared/languages/l10n
      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        working-directory: ./base_flutter
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        working-directory: ./base_flutter
        run: flutter test
